---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: ubuntu-12.04
    box_url: https://mopub-virtual-machines.s3.amazonaws.com/ubuntu-12.04.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
    - recipe[runit]
- name: runit-service
  run_list:
    - recipe[runit::default]
    - recipe[runit_test::test_runit_service]
